CREATE DATABASE EduSys
GO

USE EduSys
GO

CREATE TABLE NhanVien
(
 MaNV NVARCHAR(20) NOT NULL,
 MatKhau NVARCHAR(50) NOT NULL,
 HoTen NVARCHAR(50) NOT NULL,
 VaiTro BIT DEFAULT 0,
 PRIMARY KEY(MaNV)
)
GO

CREATE TABLE ChuyenDe
(
 MaCD NCHAR(5) NOT NULL,
 TenCD NVARCHAR(50) NOT NULL,
 HocPhi FLOAT NOT NULL,
 ThoiLuong INT NOT NULL,
 Hinh NVARCHAR(50) NOT NULL,
 MoTa NVARCHAR(255) NOT NULL,
 PRIMARY KEY(MaCD)
)
GO

CREATE TABLE KhoaHoc
(
 MaKH INT IDENTITY(1,1) NOT NULL,
 MaCD NCHAR(5) NOT NULL,
 HocPhi FLOAT NOT NULL,
 ThoiLuong INT NOT NULL,
 NgayKG DATE NOT NULL,
 GhiChu NVARCHAR(255) NULL,
 MaNV NVARCHAR(20) NOT NULL,
 NgayTao DATE DEFAULT getdate(),
 PRIMARY KEY(MaKH),
 FOREIGN KEY (MaCD) REFERENCES ChuyenDe(MaCD) ON DELETE NO ACTION ON UPDATE CASCADE,
 FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
)
GO

CREATE TABLE NguoiHoc
(
 MaNH NCHAR(7) NOT NULL,
 HoTen NVARCHAR(50) NOT NULL,
 GioiTinh BIT DEFAULT 1,
 NgaySinh DATE NOT NULL,
 DienThoai NVARCHAR(24) NOT NULL,
 Email NVARCHAR(50) NOT NULL,
 GhiChu NVARCHAR(255) NOT NULL,
 MaNV NVARCHAR(20) NOT NULL,
 NgayDK DATE DEFAULT getdate(),
 PRIMARY KEY(MaNH),
 FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
)
GO

CREATE TABLE HocVien
(
 MaHV INT IDENTITY(1,1) NOT NULL,
 MaKH INT NOT NULL,
 MaNH NCHAR(7) NOT NULL,
 Diem FLOAT DEFAULT -1,
 PRIMARY KEY(MaHV),
 FOREIGN KEY (MaKH) REFERENCES KhoaHoc(MaKH) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (MaNH) REFERENCES NguoiHoc(MaNH) ON DELETE NO ACTION ON UPDATE NO ACTION
)
GO