CREATE DATABASE POLYCLOTHES
GO
USE POLYCLOTHES
GO
CREATE TABLE NHANVIEN(
    ID_NV INT IDENTITY(1,1) PRIMARY KEY,
	MaNV VARCHAR(250) NOT NULL,
    TenNV NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(150) NOT NULL,
    Sdt VARCHAR(10) NOT NULL,
    Email VARCHAR(50),
    GioiTinh INT NOT NULL,
    TaiKhoan VARCHAR(50) NOT NULL,
    MatKhau VARCHAR(20) NOT NULL,
    VaiTro NVARCHAR(50) NOT NULL,
    TrangThai INT NOT NULL
);
CREATE TABLE KHACHHANG(
    ID_KH INT IDENTITY(1,1) PRIMARY KEY,
	MaKH VARCHAR(250) NOT NULL,
    TenKH NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(150) NOT NULL,
    Sdt VARCHAR(10) NOT NULL,
    Email VARCHAR(50),
    GioiTinh INT NOT NULL,
    TrangThai INT NOT NULL
);
CREATE TABLE SANPHAM(
	ID_SP INT IDENTITY(1,1) PRIMARY KEY,
	MaSP VARCHAR(250) NOT NULL,
	TenSP NVARCHAR(100) NOT NULL,
	TrangThai BIT NOT NULL
);
CREATE TABLE BienThe_SANPHAM(
    ID_BienTheSP INT IDENTITY(1,1) PRIMARY KEY,
	ID_SP INT NOT NULL,
    ID_LoaiSP INT NOT NULL,
    ID_Mau INT NOT NULL,
    ID_Size INT NOT NULL,
    ID_ChatLieu INT NOT NULL,
	MaBienTheSP VARCHAR(250) NOT NULL,
    SoLuong INT NOT NULL,
    GiaSP MONEY NOT NULL,
    TrangThai BIT NOT NULL
);
CREATE TABLE LOAISANPHAM(
    ID_LoaiSP INT IDENTITY(1,1) PRIMARY KEY,
	MaLoaiSP VARCHAR(250) NOT NULL,
    TenLoaiSP NVARCHAR(100) NOT NULL,
    TrangThai BIT NOT NULL
);
CREATE TABLE MAU(
    ID_Mau INT IDENTITY(1,1) PRIMARY KEY,
    MaMau VARCHAR(250) NOT NULL,
    TenMau NVARCHAR(100) NOT NULL,
    TrangThai BIT NOT NULL
);
CREATE TABLE SIZE(
    ID_Size INT IDENTITY(1,1) PRIMARY KEY,
    MaSize VARCHAR(250) NOT NULL,
    TenSize NVARCHAR(100) NOT NULL,
    TrangThai BIT NOT NULL
);
CREATE TABLE CHATLIEU(
    ID_CL INT IDENTITY(1,1) PRIMARY KEY,
    MaChatLieu VARCHAR(250) NOT NULL,
    TenCL NVARCHAR(100) NOT NULL,
    TrangThai BIT NOT NULL
);
CREATE TABLE HOADON(
    ID_HD INT IDENTITY(1,1) PRIMARY KEY,
	MaHD VARCHAR(250)  NOT NULL,
    ID_NV INT NOT NULL,
    ID_KH INT NOT NULL,
	NgayTao DATE DEFAULT GETDATE() NOT NULL,
    TongTien MONEY NOT NULL,
    MaGiamGia VARCHAR(10),
    GhiChu NVARCHAR(150),
    HinhThucThanhToan NVARCHAR(50),
    TrangThai BIT NOT NULL
);
CREATE TABLE HOADON_CT(
    ID_HDCT INT IDENTITY(1,1) PRIMARY KEY,
	MaHDCT VARCHAR(250) NOT NULL,
    ID_BienTheSP INT NOT NULL,
    ID_HD INT NOT NULL,
    SoLuong INT NOT NULL,
    TongTien MONEY NOT NULL, 
    TrangThai BIT NOT NULL
);
CREATE TABLE DOTGIAMGIA(
	MaDotGiamGia VARCHAR(10) PRIMARY KEY,
	TenDot NVARCHAR(100),
	NgayBatDau DATE,
	NgayKetThuc DATE,
	PhanTramGiam INT,
	DieuKien FLOAT, --số tiền tối thiểu để hóa đơn được giảm
	TrangThai INT  -- 0 còn hạn, 1 hết hạn
);

ALTER TABLE BienThe_SANPHAM ADD CONSTRAINT fk_btsp_sp FOREIGN KEY (ID_SP) REFERENCES SANPHAM (ID_SP);
ALTER TABLE BienThe_SANPHAM ADD CONSTRAINT fk_btsp_loaisp FOREIGN KEY (ID_LoaiSP) REFERENCES LOAISANPHAM (ID_LoaiSP);
ALTER TABLE BienThe_SANPHAM ADD CONSTRAINT fk_btsp_mau FOREIGN KEY (ID_Mau) REFERENCES MAU (ID_Mau);
ALTER TABLE BienThe_SANPHAM ADD CONSTRAINT fk_btsp_size FOREIGN KEY (ID_Size) REFERENCES SIZE (ID_Size);
ALTER TABLE BienThe_SANPHAM ADD CONSTRAINT fk_btsp_chatlieu FOREIGN KEY (ID_ChatLieu) REFERENCES CHATLIEU (ID_CL);
ALTER TABLE HOADON ADD CONSTRAINT fk_hoadon_nhanvien FOREIGN KEY (ID_NV) REFERENCES NHANVIEN (ID_NV);
ALTER TABLE HOADON ADD CONSTRAINT fk_hoadon_khachhang FOREIGN KEY (ID_KH) REFERENCES KHACHHANG (ID_KH);
ALTER TABLE HOADON ADD CONSTRAINT fk_hoadon_dotgiamgia FOREIGN KEY (MaGiamGia) REFERENCES DOTGIAMGIA(MaDotGiamGia);
ALTER TABLE HOADON_CT ADD CONSTRAINT fk_hdct_btsp FOREIGN KEY (ID_BienTheSP) REFERENCES BienThe_SANPHAM (ID_BienTheSP);
ALTER TABLE HOADON_CT ADD CONSTRAINT fk_hdct_hoadon FOREIGN KEY (ID_HD) REFERENCES HOADON (ID_HD);
GO

INSERT INTO NHANVIEN VALUES('NV01',N'Nguyễn Thu Nghĩa',N'Đông Anh, Hà Nội','0834045324','nghiant12@gmail.com',1,'nghiant12','nghia123',N'Quản lý',0);
INSERT INTO NHANVIEN VALUES('NV02',N'Lê Văn Nam',N'Bắc Giang','0931037777','namlv@gmail.com',0,'namlv04','namdeptrai',N'Nhân viên',0);
INSERT INTO NHANVIEN VALUES('NV03',N'Vũ Thế Anh',N'Thanh Hóa','0306082004','anhvt@gmail.com',0,'theanh68','theanh123',N'Nhân viên',1);
INSERT INTO NHANVIEN VALUES('NV04',N'Bùi Cao Minh',N'Mê Linh, Hà Nội','0378902004','minhbc@gmail.com',0,'minhcodoc','minh123',N'Nhân viên',0);
SELECT * FROM NHANVIEN

GO
INSERT INTO KHACHHANG VALUES('KH01',N'Nguyễn Thu Nghĩa',N'Đông Anh, Hà Nội','0834045324','nghiant12@gmail.com',1,0);
INSERT INTO KHACHHANG VALUES('KH02',N'Lê Văn Nam',N'Bắc Giang','0931037777','namlv@gmail.com',0,0);
INSERT INTO KHACHHANG VALUES('KH03',N'Vũ Thế Anh',N'Thanh Hóa','0306082004','anhvt@gmail.com',0,1);
INSERT INTO KHACHHANG VALUES('KH04',N'Bùi Cao Minh',N'Mê Linh, Hà Nội','0378902004','minhbc@gmail.com',0,0);
SELECT * FROM KHACHHANG
GO
CREATE TRIGGER tr_ma_san_pham
ON SANPHAM
AFTER INSERT
AS
BEGIN
    DECLARE @id INT, @ma VARCHAR(255);
    SELECT @id = ID_SP FROM inserted;
    SET @ma = 'SP' + RIGHT('00' + CAST(@id AS VARCHAR), 3);
    UPDATE SANPHAM SET MaSP = @ma WHERE ID_SP = @id;
END;
GO
INSERT INTO SANPHAM VALUES('',N'Áo sơ mi',0);
INSERT INTO SANPHAM VALUES('',N'Áo phông',0);
INSERT INTO SANPHAM VALUES('',N'Áo cardigan',0);
INSERT INTO SANPHAM VALUES('',N'Áo pijama',0);
INSERT INTO SANPHAM VALUES('',N'Áo hoodie',0);
INSERT INTO SANPHAM VALUES('',N'Quần jean',0);
INSERT INTO SANPHAM VALUES('',N'Quần short',0);
INSERT INTO SANPHAM VALUES('',N'Quần skinny',1);
INSERT INTO SANPHAM VALUES('',N'Quần Culottes',1);
INSERT INTO SANPHAM VALUES('',N'Chân váy jean',0);
INSERT INTO SANPHAM VALUES('',N'Chân váy dài xếp tầng',0);
INSERT INTO SANPHAM VALUES('',N'Chân váy dáng suông',0);
INSERT INTO SANPHAM VALUES('',N'Chân váy chữ A',0);
SELECT * FROM SANPHAM
GO
INSERT INTO LOAISANPHAM VALUES('AO',N'Áo',0);
INSERT INTO LOAISANPHAM VALUES('QUAN',N'Quần',0);
INSERT INTO LOAISANPHAM VALUES('CHVAY',N'Chân váy',0);
SELECT * FROM LOAISANPHAM
GO
CREATE TRIGGER tr_ma_mau
ON MAU
AFTER INSERT
AS
BEGIN
    DECLARE @id INT, @ma VARCHAR(255);
    SELECT @id = ID_Mau FROM inserted;
    SET @ma = 'M' + RIGHT('0' + CAST(@id AS VARCHAR), 2);
    UPDATE MAU SET MaMau = @ma WHERE ID_Mau = @id;
END;
GO
INSERT INTO MAU VALUES('',N'Đen',0);
INSERT INTO MAU VALUES('',N'Trắng',0);
INSERT INTO MAU VALUES('',N'Xám',0);
INSERT INTO MAU VALUES('',N'Hồng',0);
INSERT INTO MAU VALUES('',N'Tím pastel',0);
INSERT INTO MAU VALUES('',N'Xanh mint',0);
SELECT * FROM MAU
GO
CREATE TRIGGER tr_ma_size
ON SIZE
AFTER INSERT
AS
BEGIN
    DECLARE @id INT, @ma VARCHAR(255);
    SELECT @id = ID_Size FROM inserted;
    SET @ma = 'S' + RIGHT('0' + CAST(@id AS VARCHAR), 2);
    UPDATE SIZE SET MaSize = @ma WHERE ID_Size = @id;
END;
GO
INSERT INTO SIZE VALUES('','S',0);
INSERT INTO SIZE VALUES('','M',0);
INSERT INTO SIZE VALUES('','L',0);
INSERT INTO SIZE VALUES('','XL',0);
SELECT * FROM SIZE
GO
CREATE TRIGGER tr_ma_chat_lieu
ON CHATLIEU
AFTER INSERT
AS
BEGIN
    DECLARE @id INT, @ma VARCHAR(255);
    SELECT @id = ID_CL FROM inserted;
    SET @ma = 'CL' + RIGHT('0' + CAST(@id AS VARCHAR), 2);
    UPDATE CHATLIEU SET MaChatLieu = @ma WHERE ID_CL = @id;
END;
GO
INSERT INTO CHATLIEU VALUES('','Cotton',0);
INSERT INTO CHATLIEU VALUES('','Lụa',0);
INSERT INTO CHATLIEU VALUES('','Jean',0);
INSERT INTO CHATLIEU VALUES('','Kaki',0);
INSERT INTO CHATLIEU VALUES('','Len',0);
SELECT * FROM CHATLIEU
GO
CREATE TRIGGER tr_ma_bien_the_sp
ON BienThe_SANPHAM
AFTER INSERT
AS
BEGIN
    DECLARE @id_btsp INT, @ma VARCHAR(255);
    SELECT @id_btsp = ID_BienTheSP FROM inserted;
    SET @ma = 'BT' + RIGHT('00' + CAST(@id_btsp AS VARCHAR), 3);
    UPDATE BienThe_SANPHAM SET MaBienTheSP = @ma WHERE ID_BienTheSP = @id_btsp;
END;
GO
INSERT INTO BienThe_SANPHAM VALUES(1,1,3,2,1,'',25,250000,0);
INSERT INTO BienThe_SANPHAM VALUES(1,1,1,1,1,'',20,250000,0);
INSERT INTO BienThe_SANPHAM VALUES(1,1,6,3,2,'',30,350000,0);
INSERT INTO BienThe_SANPHAM VALUES(2,1,4,2,1,'',50,125000,0);
INSERT INTO BienThe_SANPHAM VALUES(2,1,5,2,1,'',75,175000,0);
INSERT INTO BienThe_SANPHAM VALUES(2,1,2,2,1,'',100,150000,0);
INSERT INTO BienThe_SANPHAM VALUES(3,1,4,3,5,'',15,400000,0);
INSERT INTO BienThe_SANPHAM VALUES(4,1,3,4,2,'',10,250000,0);
INSERT INTO BienThe_SANPHAM VALUES(5,1,1,2,1,'',20,250000,0);
INSERT INTO BienThe_SANPHAM VALUES(6,2,3,2,3,'',30,250000,0);
INSERT INTO BienThe_SANPHAM VALUES(6,2,1,1,3,'',30,250000,0);
INSERT INTO BienThe_SANPHAM VALUES(10,3,1,2,3,'',45,350000,0);
INSERT INTO BienThe_SANPHAM VALUES(11,3,2,2,2,'',60,250000,0);
INSERT INTO BienThe_SANPHAM VALUES(11,3,6,3,2,'',20,210000,0);
INSERT INTO BienThe_SANPHAM VALUES(13,3,5,1,4,'',15,160000,0);
INSERT INTO BienThe_SANPHAM VALUES(13,3,1,1,3,'',10,150000,0);
SELECT * FROM BienThe_SANPHAM
GO
INSERT INTO DOTGIAMGIA VALUES('BFRIDAY01',N'Black Friday','2023-11-23','2023-11-25',20,500000,0);
INSERT INTO DOTGIAMGIA VALUES('MRYCHRTM23',N'Merry Christmas 23','2023-12-15','2023-12-25',25,450000,0);
INSERT INTO DOTGIAMGIA VALUES('TDL2024',N'Tết Dương lịch 2024','2023-12-30','2024-01-05',15,250000,0);
SELECT * FROM DOTGIAMGIA
--INSERT INTO HOADON VALUES ('HD01',1,3,GETDATE(),'','BFRIDAY01','','',0)
SELECT * FROM HOADON