CREATE DATABASE POLYCLOTHES
GO
USE POLYCLOTHES
GO
CREATE TABLE NHANVIEN(
    ID_NV INT IDENTITY(1,1) PRIMARY KEY,
	MaNV VARCHAR(250) ,
    TenNV NVARCHAR(100) ,
    DiaChi NVARCHAR(150) ,
    Sdt VARCHAR(10) ,
    Email VARCHAR(50),
    GioiTinh INT ,
    TaiKhoan VARCHAR(50) ,
    MatKhau VARCHAR(20) ,
    VaiTro NVARCHAR(50) ,
    TrangThai INT 
);
CREATE TABLE KHACHHANG(
    ID_KH INT IDENTITY(1,1) PRIMARY KEY,
	MaKH VARCHAR(250) ,
    TenKH NVARCHAR(100) ,
    DiaChi NVARCHAR(150) ,
    Sdt VARCHAR(10) ,
    Email VARCHAR(50),
    GioiTinh INT ,
    TrangThai INT 
);
CREATE TABLE SANPHAM(
	ID_SP INT IDENTITY(1,1) PRIMARY KEY,
	MaSP VARCHAR(250) ,
	TenSP NVARCHAR(100) ,
	TrangThai BIT 
);
CREATE TABLE BienThe_SANPHAM(
    ID_BienTheSP INT IDENTITY(1,1) PRIMARY KEY,
	ID_SP INT ,
    ID_LoaiSP INT ,
    ID_Mau INT ,
    ID_Size INT ,
    ID_ChatLieu INT ,
	MaBienTheSP VARCHAR(250) ,
    SoLuong INT ,
    GiaSP MONEY ,
    TrangThai BIT 
);
CREATE TABLE LOAISANPHAM(
    ID_LoaiSP INT IDENTITY(1,1) PRIMARY KEY,
	MaLoaiSP VARCHAR(250) ,
    TenLoaiSP NVARCHAR(100) ,
    TrangThai BIT 
);
CREATE TABLE MAU(
    ID_Mau INT IDENTITY(1,1) PRIMARY KEY,
    MaMau VARCHAR(250) ,
    TenMau NVARCHAR(100) ,
    TrangThai BIT 
);
CREATE TABLE SIZE(
    ID_Size INT IDENTITY(1,1) PRIMARY KEY,
    MaSize VARCHAR(250) ,
    TenSize NVARCHAR(100) ,
    TrangThai BIT 
);
CREATE TABLE CHATLIEU(
    ID_CL INT IDENTITY(1,1) PRIMARY KEY,
    MaChatLieu VARCHAR(250) ,
    TenCL NVARCHAR(100) ,
    TrangThai BIT 
);
CREATE TABLE HOADON(
    ID_HD INT IDENTITY(1,1) PRIMARY KEY,
	MaHD VARCHAR(250)  ,
    ID_NV INT ,
    ID_KH INT ,
	NgayTao DATE DEFAULT GETDATE() ,
    TongTien MONEY ,
    MaGiamGia VARCHAR(10),
    GhiChu NVARCHAR(150),
    HinhThucThanhToan NVARCHAR(50),
    TrangThai BIT 
);
CREATE TABLE HOADON_CT(
    ID_HDCT INT IDENTITY(1,1) PRIMARY KEY,
	MaHDCT VARCHAR(250) ,
    ID_BienTheSP INT ,
    ID_HD INT ,
    SoLuong INT ,
    TongTien MONEY , 
    TrangThai BIT 
);
CREATE TABLE DOTGIAMGIA(
	MaDotGiamGia VARCHAR(10) PRIMARY KEY,
	TenDot NVARCHAR(100),
	NgayBatDau DATE,
	NgayKetThuc DATE,
	PhanTramGiam INT,
	DieuKien FLOAT, --số tiền tối thiểu để hóa đơn được giảm
	TrangThai INT  -- 0 còn hạn, 1 hết hạn
);

ALTER TABLE BienThe_SANPHAM ADD CONSTRAINT fk_btsp_sp FOREIGN KEY (ID_SP) REFERENCES SANPHAM (ID_SP);
ALTER TABLE BienThe_SANPHAM ADD CONSTRAINT fk_btsp_loaisp FOREIGN KEY (ID_LoaiSP) REFERENCES LOAISANPHAM (ID_LoaiSP);
ALTER TABLE BienThe_SANPHAM ADD CONSTRAINT fk_btsp_mau FOREIGN KEY (ID_Mau) REFERENCES MAU (ID_Mau);
ALTER TABLE BienThe_SANPHAM ADD CONSTRAINT fk_btsp_size FOREIGN KEY (ID_Size) REFERENCES SIZE (ID_Size);
ALTER TABLE BienThe_SANPHAM ADD CONSTRAINT fk_btsp_chatlieu FOREIGN KEY (ID_ChatLieu) REFERENCES CHATLIEU (ID_CL);
ALTER TABLE HOADON ADD CONSTRAINT fk_hoadon_nhanvien FOREIGN KEY (ID_NV) REFERENCES NHANVIEN (ID_NV);
ALTER TABLE HOADON ADD CONSTRAINT fk_hoadon_khachhang FOREIGN KEY (ID_KH) REFERENCES KHACHHANG (ID_KH);
ALTER TABLE HOADON ADD CONSTRAINT fk_hoadon_dotgiamgia FOREIGN KEY (MaGiamGia) REFERENCES DOTGIAMGIA(MaDotGiamGia);
ALTER TABLE HOADON_CT ADD CONSTRAINT fk_hdct_btsp FOREIGN KEY (ID_BienTheSP) REFERENCES BienThe_SANPHAM (ID_BienTheSP);
ALTER TABLE HOADON_CT ADD CONSTRAINT fk_hdct_hoadon FOREIGN KEY (ID_HD) REFERENCES HOADON (ID_HD);
GO
CREATE TRIGGER tr_ma_nv
ON NHANVIEN
AFTER INSERT
AS
BEGIN
    DECLARE @id_nv INT, @ma VARCHAR(255);
    SELECT @id_nv = ID_NV FROM inserted;
    SET @ma = 'NV' + RIGHT('00' + CAST(@id_nv AS VARCHAR), 3);
    UPDATE NHANVIEN SET MaNV = @ma WHERE ID_NV = @id_nv;
END;
GO
INSERT INTO NHANVIEN VALUES('',N'Nguyễn Thu Nghĩa',N'Đông Anh, Hà Nội','0834045324','nghiant12@gmail.com',1,'nghiant12','nghia123',N'Quản lý',0);
INSERT INTO NHANVIEN VALUES('',N'Lê Văn Nam',N'Bắc Giang','0931037777','namlv@gmail.com',0,'namlv04','namdeptrai',N'Nhân viên',0);
INSERT INTO NHANVIEN VALUES('',N'Vũ Thế Anh',N'Thanh Hóa','0306082004','anhvt@gmail.com',0,'theanh68','theanh123',N'Nhân viên',1);
INSERT INTO NHANVIEN VALUES('',N'Bùi Cao Minh',N'Mê Linh, Hà Nội','0378902004','minhbc@gmail.com',0,'minhcodoc','minh123',N'Nhân viên',0);
SELECT * FROM NHANVIEN
GO
CREATE TRIGGER tr_ma_kh
ON KHACHHANG
AFTER INSERT
AS
BEGIN
    DECLARE @id_kh INT, @ma VARCHAR(255);
    SELECT @id_kh = ID_KH FROM inserted;
    SET @ma = 'KH' + RIGHT('00' + CAST(@id_kh AS VARCHAR), 3);
    UPDATE KHACHHANG SET MaKH = @ma WHERE ID_KH = @id_kh;
END;
GO
INSERT INTO KHACHHANG VALUES('',N'Nguyễn Thu Nghĩa',N'Đông Anh, Hà Nội','0834045324','nghiant12@gmail.com',1,0);
INSERT INTO KHACHHANG VALUES('',N'Lê Văn Nam',N'Bắc Giang','0931037777','namlv@gmail.com',0,0);
INSERT INTO KHACHHANG VALUES('',N'Vũ Thế Anh',N'Thanh Hóa','0306082004','anhvt@gmail.com',0,1);
INSERT INTO KHACHHANG VALUES('',N'Bùi Cao Minh',N'Mê Linh, Hà Nội','0378902004','minhbc@gmail.com',0,0);
SELECT * FROM KHACHHANG
GO
CREATE TRIGGER tr_ma_san_pham
ON SANPHAM
AFTER INSERT
AS
BEGIN
    DECLARE @id INT, @ma VARCHAR(255);
    SELECT @id = ID_SP FROM inserted;
    SET @ma = 'SP' + RIGHT('00' + CAST(@id AS VARCHAR), 3);
    UPDATE SANPHAM SET MaSP = @ma WHERE ID_SP = @id;
END;
GO
INSERT INTO SANPHAM VALUES('',N'Áo sơ mi',1);
INSERT INTO SANPHAM VALUES('',N'Áo phông',1);
INSERT INTO SANPHAM VALUES('',N'Áo cardigan',1);
INSERT INTO SANPHAM VALUES('',N'Áo pijama',1);
INSERT INTO SANPHAM VALUES('',N'Áo hoodie',1);
INSERT INTO SANPHAM VALUES('',N'Quần jean',1);
INSERT INTO SANPHAM VALUES('',N'Quần short',0);
INSERT INTO SANPHAM VALUES('',N'Quần skinny',0);
INSERT INTO SANPHAM VALUES('',N'Quần Culottes',0);
INSERT INTO SANPHAM VALUES('',N'Chân váy jean',1);
INSERT INTO SANPHAM VALUES('',N'Chân váy dài xếp tầng',1);
INSERT INTO SANPHAM VALUES('',N'Chân váy dáng suông',0);
INSERT INTO SANPHAM VALUES('',N'Chân váy chữ A',1);
SELECT * FROM SANPHAM
GO
INSERT INTO LOAISANPHAM VALUES('AO',N'Áo',1);
INSERT INTO LOAISANPHAM VALUES('QUAN',N'Quần',1);
INSERT INTO LOAISANPHAM VALUES('CHVAY',N'Chân váy',1);
SELECT * FROM LOAISANPHAM
GO
CREATE TRIGGER tr_ma_mau
ON MAU
AFTER INSERT
AS
BEGIN
    DECLARE @id INT, @ma VARCHAR(255);
    SELECT @id = ID_Mau FROM inserted;
    SET @ma = 'M' + RIGHT('0' + CAST(@id AS VARCHAR), 2);
    UPDATE MAU SET MaMau = @ma WHERE ID_Mau = @id;
END;
GO
INSERT INTO MAU VALUES('',N'Đen',1);
INSERT INTO MAU VALUES('',N'Trắng',1);
INSERT INTO MAU VALUES('',N'Xám',1);
INSERT INTO MAU VALUES('',N'Hồng',1);
INSERT INTO MAU VALUES('',N'Tím pastel',1);
INSERT INTO MAU VALUES('',N'Xanh mint',1);
SELECT * FROM MAU
GO
CREATE TRIGGER tr_ma_size
ON SIZE
AFTER INSERT
AS
BEGIN
    DECLARE @id INT, @ma VARCHAR(255);
    SELECT @id = ID_Size FROM inserted;
    SET @ma = 'S' + RIGHT('0' + CAST(@id AS VARCHAR), 2);
    UPDATE SIZE SET MaSize = @ma WHERE ID_Size = @id;
END;
GO
INSERT INTO SIZE VALUES('','S',1);
INSERT INTO SIZE VALUES('','M',1);
INSERT INTO SIZE VALUES('','L',1);
INSERT INTO SIZE VALUES('','XL',1);
SELECT * FROM SIZE
GO
CREATE TRIGGER tr_ma_chat_lieu
ON CHATLIEU
AFTER INSERT
AS
BEGIN
    DECLARE @id INT, @ma VARCHAR(255);
    SELECT @id = ID_CL FROM inserted;
    SET @ma = 'CL' + RIGHT('0' + CAST(@id AS VARCHAR), 2);
    UPDATE CHATLIEU SET MaChatLieu = @ma WHERE ID_CL = @id;
END;
GO
INSERT INTO CHATLIEU VALUES('',N'Cotton',1);
INSERT INTO CHATLIEU VALUES('',N'Lụa',1);
INSERT INTO CHATLIEU VALUES('',N'Jean',1);
INSERT INTO CHATLIEU VALUES('',N'Kaki',1);
INSERT INTO CHATLIEU VALUES('',N'Len',1);
SELECT * FROM CHATLIEU
GO
CREATE TRIGGER tr_ma_bien_the_sp
ON BienThe_SANPHAM
AFTER INSERT
AS
BEGIN
    DECLARE @id_btsp INT, @ma VARCHAR(255);
    SELECT @id_btsp = ID_BienTheSP FROM inserted;
    SET @ma = 'BT' + RIGHT('00' + CAST(@id_btsp AS VARCHAR), 3);
    UPDATE BienThe_SANPHAM SET MaBienTheSP = @ma WHERE ID_BienTheSP = @id_btsp;
END;
GO
INSERT INTO BienThe_SANPHAM VALUES(1,1,3,2,1,'',25,250000,1);
INSERT INTO BienThe_SANPHAM VALUES(1,1,1,1,1,'',20,250000,1);
INSERT INTO BienThe_SANPHAM VALUES(1,1,6,3,2,'',30,350000,1);
INSERT INTO BienThe_SANPHAM VALUES(2,1,4,2,1,'',50,125000,1);
INSERT INTO BienThe_SANPHAM VALUES(2,1,5,2,1,'',75,175000,1);
INSERT INTO BienThe_SANPHAM VALUES(2,1,2,2,1,'',100,150000,1);
INSERT INTO BienThe_SANPHAM VALUES(3,1,4,3,5,'',15,400000,1);
INSERT INTO BienThe_SANPHAM VALUES(4,1,3,4,2,'',10,250000,1);
INSERT INTO BienThe_SANPHAM VALUES(5,1,1,2,1,'',20,250000,1);
INSERT INTO BienThe_SANPHAM VALUES(6,2,3,2,3,'',30,250000,1);
INSERT INTO BienThe_SANPHAM VALUES(6,2,1,1,3,'',30,250000,1);
INSERT INTO BienThe_SANPHAM VALUES(10,3,1,2,3,'',45,350000,1);
INSERT INTO BienThe_SANPHAM VALUES(11,3,2,2,2,'',60,250000,1);
INSERT INTO BienThe_SANPHAM VALUES(11,3,6,3,2,'',20,210000,1);
INSERT INTO BienThe_SANPHAM VALUES(13,3,5,1,4,'',15,160000,1);
INSERT INTO BienThe_SANPHAM VALUES(13,3,1,1,3,'',10,150000,1);
SELECT * FROM BienThe_SANPHAM;
GO
INSERT INTO DOTGIAMGIA VALUES('',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO DOTGIAMGIA VALUES('BFRIDAY01',N'Black Friday','2023-11-23','2023-11-25',20,500000,0);
INSERT INTO DOTGIAMGIA VALUES('MRYCHRTM23',N'Merry Christmas 23','2023-12-15','2023-12-25',25,450000,0);
INSERT INTO DOTGIAMGIA VALUES('TDL2024',N'Tết Dương lịch 2024','2023-12-30','2024-01-05',15,250000,0);
SELECT * FROM DOTGIAMGIA
GO
CREATE TRIGGER tr_ma_hd
ON HOADON
AFTER INSERT
AS
BEGIN
    DECLARE @id_hd INT, @ma VARCHAR(255);
    SELECT @id_hd = ID_HD FROM inserted;
    SET @ma = 'HD' + RIGHT('00' + CAST(@id_hd AS VARCHAR), 3);
    UPDATE HOADON SET MaHD = @ma WHERE ID_HD = @id_hd;
END;
GO
INSERT INTO HOADON VALUES ('',1,3,GETDATE(),'1000000','','',N'Tiền mặt',1);
INSERT INTO HOADON VALUES ('',2,2,GETDATE(),'5000000','','',N'Chuyển khoản',1);
INSERT INTO HOADON VALUES ('',3,1,GETDATE(),'2500000','','',N'Chuyển khoản',1);
INSERT INTO HOADON VALUES ('',4,4,GETDATE(),'4000000','','',N'Tiền mặt',1);
INSERT INTO HOADON VALUES ('',1,1,GETDATE(),'1500000','','',N'Tiền mặt',1);
INSERT INTO HOADON VALUES ('',3,2,GETDATE(),'2900000','','',N'Chuyển khoản',1);
SELECT * FROM HOADON
GO
CREATE TRIGGER tr_ma_hdct
ON HOADON_CT
AFTER INSERT
AS
BEGIN
    DECLARE @id_hdct INT, @ma VARCHAR(255);
    SELECT @id_hdct = ID_HDCT FROM inserted;
    SET @ma = 'HC' + RIGHT('00' + CAST(@id_hdct AS VARCHAR), 3);
    UPDATE HOADON_CT SET MaHDCT = @ma WHERE ID_HDCT = @id_hdct;
END;
GO
INSERT INTO HOADON_CT VALUES ('',1,1,2,250000,1);
INSERT INTO HOADON_CT VALUES ('',2,1,1,100000,1);
INSERT INTO HOADON_CT VALUES ('',3,1,1,350000,1);
INSERT INTO HOADON_CT VALUES ('',4,2,1,500000,1);
INSERT INTO HOADON_CT VALUES ('',5,2,1,450000,1);
INSERT INTO HOADON_CT VALUES ('',6,2,1,550000,1);
INSERT INTO HOADON_CT VALUES ('',7,3,2,600000,1);
INSERT INTO HOADON_CT VALUES ('',8,3,2,150000,1);
INSERT INTO HOADON_CT VALUES ('',9,3,1,300000,1);
SELECT * FROM HOADON_CT

---------
SELECT HOADON.MAHD,NHANVIEN.MANV,KHACHHANG.TENKH,HOADON.NGAYTAO,HOADON.TONGTIEN
FROM HOADON
INNER JOIN NHANVIEN ON NHANVIEN.ID_NV = HOADON.ID_NV
INNER JOIN KHACHHANG ON KHACHHANG.ID_KH = HOADON.ID_KH
--
SELECT TOP (5) sp.TenSP, SUM(hdct.SoLuong) AS TongSoLuongBanDuoc
FROM HOADON_CT hdct
inner join BienThe_SANPHAM btsp on btsp.ID_BienTheSP = hdct.ID_BienTheSP
inner join SANPHAM sp on sp.ID_SP = btsp.ID_SP 
GROUP BY TenSP
ORDER BY TongSoLuongBanDuoc DESC
--
SELECT NgayTao,TongTien FROM HOADON
--
SELECT TOP (3) k.MaKH, k.TenKH, SUM(h.TongTien) AS TongTienMua 
FROM HOADON h 
INNER JOIN KHACHHANG k ON h.ID_KH = k.ID_KH
GROUP BY k.MaKH, k.TenKH
ORDER BY TongTienMua DESC
--
SELECT SANPHAM.MaSP,SANPHAM.TENSP,
HOADON_CT.SoLuong,BIENTHE_SANPHAM.GiaSP
FROM HOADON_CT
inner join BIENTHE_SANPHAM on BIENTHE_SANPHAM.ID_BienTheSP = HOADON_CT.ID_BienTheSP
inner join SANPHAM on SANPHAM.ID_SP = BIENTHE_SANPHAM.ID_SP
inner join HOADON on HOADON.ID_HD = HOADON_CT.ID_HD
inner join DOTGIAMGIA on DOTGIAMGIA.MaDotGiamGia = HOADON.MaGiamGia
WHERE HOADON.MaHD like 'HD001'
--
SELECT HOADON.MaHD,HOADON.NgayTao,
NHANVIEN.MaNV,KHACHHANG.TenKH,DOTGIAMGIA.MaDotGiamGia,
HOADON.TrangThai,HOADON.HinhThucThanhToan,HOADON.GhiChu
FROM HOADON
inner join NHANVIEN on NHANVIEN.ID_NV = HOADON.ID_NV
inner join KHACHHANG on KHACHHANG.ID_KH = HOADON.ID_KH
inner join DOTGIAMGIA on DOTGIAMGIA.MaDotGiamGia = HOADON.MaGiamGia
--
SELECT HOADON.MaHD,HOADON.NgayTao,
NHANVIEN.MaNV,KHACHHANG.TenKH,DOTGIAMGIA.MaDotGiamGia,
HOADON.TrangThai
FROM HOADON
inner join NHANVIEN on NHANVIEN.ID_NV = HOADON.ID_NV
inner join KHACHHANG on KHACHHANG.ID_KH = HOADON.ID_KH
inner join DOTGIAMGIA on DOTGIAMGIA.MaDotGiamGia = HOADON.MaGiamGia